force-app/main/default/objects/ERDC_Card__c/ERDC_Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERDC_Card__c/fields/ERDC_Available_Trips__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Available_Trips__c</fullName>
    <description>This field indicates the number of available trips that can be made with this card.</description>
    <inlineHelpText>This field indicates the number of available trips that can be made with this card.</inlineHelpText>
    <label>Available_Trips</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ERDC_Line__c/ERDC_Line__c.object-meta.xml
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>ERDC_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERDC_Station__c/ERDC_Station__c.object-meta.xml
<CustomObject>
    <label>Station</label>
    <nameField>
        <label>Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERDC_Station__c/fields/ERDC_Line__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field indicates the transport line.</description>
    <label>Line</label>
    <referenceTo>ERDC_Line__c</referenceTo>
    <relationshipName>LineStations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERDC_Trip__c/ERDC_Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>Trip-{0000000}</displayFormat>
        <label>Trip Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERDC_Trip__c/fields/ERDC_Card__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Card</label>
    <referenceTo>ERDC_Card__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERDC_Trip__c/fields/ERDC_Line__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line</label>
    <referenceTo>ERDC_Line__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERDC_Trip__c/fields/ERDC_Station__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Station</label>
    <referenceTo>ERDC_Station__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFID_TicketValidationMachine__e/RFID_TicketValidationMachine__e.object-meta.xml
<CustomObject>
    <description>This platform event takes the input from ticket validation machines.</description>
    <label>Ticket Validation Machine Event</label>
    <pluralLabel>Ticket Validation Machines Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/RFID_TicketValidationMachine__e/fields/RFID_Available_Trips__c.field-meta.xml
<CustomField>
    <fullName>RFID_Available_Trips__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Trips</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RFID_TicketValidationMachine__e/fields/RFID_Station__c.field-meta.xml
<CustomField>
    <fullName>RFID_Station__c</fullName>
    <label>Station</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RFID_TicketValidationMachine__e/fields/RFID_Tag__c.field-meta.xml
<CustomField>
    <fullName>RFID_Tag__c</fullName>
    <description>This field stores the unique ID Tag of a Card, which was read by the Validation Machine.</description>
    <label>ID Tag</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Event_TicketValidationMachineManagement.cls
/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-21
* @description This is a helper class for Event_TicketValidationMachineManagement trigger. It supports only AFTER INSERT context.
********************************************************************************************************/
public without sharing class Event_TicketValidationMachineManagement implements TriggerInterface {
  public void beforeInsert(List<sObject> newList) {
  }

  public void afterInsert(List<sObject> newList) {
    Event_TicketValidationMachineManagement.recalcCardsInsertTrips(newList);
  }

  public void beforeUpdate(List<sObject> newList, Map<Id, sObject> oldMap) {
  }

  public void afterUpdate(List<sObject> newList, Map<Id, sObject> oldMap) {
  }

/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-21
* @description This method update fields on a Card and creates a Trip with Event data  after the Event is published.
* @param List<RFID_TicketValidationMachine__e>
********************************************************************************************************/
  public static void recalcCardsInsertTrips(List<RFID_TicketValidationMachine__e> newlist) {  
    try {
      Set<String> eventCardTags = new Set<String>();
      Set<String> eventSubstationNames= new Set<String>();
      for (RFID_TicketValidationMachine__e event : newlist) {
        eventCardTags.add(event.RFID_Tag__c);
        eventSubstationNames.add(event.RFID_Station__c);
      }

      Map<String, ERDC_Card__c> cardsByName = Event_TicketValidationMachineManagement.getCardsByName(eventCardTags);
      Map<String, ERDC_Station__c> substationsByName = Event_TicketValidationMachineManagement.getSubstationsByName(eventSubstationNames);
      if (cardsByName == null || substationsByName == null) return;

      List<ERDC_Trip__c> tripsToInsert = new List<ERDC_Trip__c>();
      List<ERDC_Card__c> cardsToUpdate = new List<ERDC_Card__c>();
      for (RFID_TicketValidationMachine__e event : newlist) {
        
        ERDC_Trip__c newTrip = new ERDC_Trip__c(
          ERDC_Station__c = substationsByName.get(event.RFID_Station__c).Id,
          ERDC_Line__c = substationsByName.get(event.RFID_Station__c).ERDC_Line__r.Id,
          ERDC_Card__c = cardsByName.get(event.RFID_Tag__c).Id
        );
        tripsToInsert.add(newTrip);

        cardsByName.get(event.RFID_Tag__c).ERDC_Available_Trips__c = event.RFID_Available_Trips__c;
        cardsToUpdate.add(cardsByName.get(event.RFID_Tag__c));
      }

      if (!cardsToUpdate.isEmpty()) update cardsToUpdate;
      if (!tripsToInsert.isEmpty()) insert tripsToInsert;
    }
    catch(Exception e) {
      LogsUtility.logMessage(e, 'Event_TicketValidationMachineManagement.updateCard');
    }
  }

/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-23
* @description This method returns a map of Cards by Cards Name
* @param Set<String>
********************************************************************************************************/
  public static  Map<String, ERDC_Card__c> getCardsByName(Set<String> cardNames) {
    if (cardNames.isEmpty()) return null;

    Map<String, ERDC_Card__c> cardsByName = new Map<String,ERDC_Card__c>();
    List<ERDC_Card__c> cards = [
      SELECT Id,
        Name,
        ERDC_Available_Trips__c
      FROM ERDC_Card__c
      WHERE ERDC_Card__c.Name IN :cardNames
    ];
    if (cards.isEmpty()) return null;

    for (ERDC_Card__c card : cards) {
      cardsByName.put(card.Name, card);   
    }
    return cardsByName;
  }

/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-23
* @description This method returns a map of Substations by Substations Name
* @param Set<String>
********************************************************************************************************/
  public static  Map<String, ERDC_Station__c> getSubstationsByName(Set<String> substationNames) {
    if (substationNames.isEmpty()) return null;

    Map<String, ERDC_Station__c> substationsByName = new Map<String,ERDC_Station__c>();
    List<ERDC_Station__c> substations = [
      SELECT Id,
        Name,
        ERDC_Line__r.Id 
      FROM ERDC_Station__c
      WHERE Name IN :substationNames
      AND RecordType.Id = :ERDC_GlobalUtilityConstants.SUBSTATION_RECORD_TYPE_ID
    ];
    if (substations.isEmpty()) return null;

    for (ERDC_Station__c substation : substations){
      substationsByName.put(substation.Name, substation);
    }
    return substationsByName;
  }
}