force-app/main/default/objects/ERDC_Line__c/ERDC_Line__c.object-meta.xml
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>ERDC_Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERDC_Line__c/fields/ERDC_Coordinates__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Coordinates__c</fullName>
    <description>This field stores the coordinates that are needed for map display.</description>
    <label>Coordinates</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ERDC_Line__c/fields/ERDC_Map_Color__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Map_Color__c</fullName>
    <label>Map Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AliceBlue</fullName>
            </value>
            <value>
                <fullName>AntiqueWhite</fullName>
            </value>
            <value>
                <fullName>Aqua</fullName>
            </value>
            <value>
                <fullName>Aquamarine</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Bisque</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>BlanchedAlmond</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>BlueViolet</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>BurlyWood</fullName>
            </value>
            <value>
                <fullName>CadetBlue</fullName>
            </value>
            <value>
                <fullName>Chartreuse</fullName>
            </value>
            <value>
                <fullName>Chocolate</fullName>
            </value>
            <value>
                <fullName>Coral</fullName>
            </value>
            <value>
                <fullName>CornflowerBlue</fullName>
            </value>
            <value>
                <fullName>Cornsilk</fullName>
            </value>
            <value>
                <fullName>Crimson</fullName>
            </value>
            <value>
                <fullName>Cyan</fullName>
            </value>
            <value>
                <fullName>DarkBlue</fullName>
            </value>
            <value>
                <fullName>DarkCyan</fullName>
            </value>
            <value>
                <fullName>DarkGoldenRod</fullName>
            </value>
            <value>
                <fullName>DarkGray</fullName>
            </value>
            <value>
                <fullName>DarkGrey</fullName>
            </value>
            <value>
                <fullName>DarkGreen</fullName>
            </value>
            <value>
                <fullName>DarkKhaki</fullName>
            </value>
            <value>
                <fullName>DarkMagenta</fullName>
            </value>
            <value>
                <fullName>DarkOliveGreen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ERDC_Station__c/ERDC_Station__c.object-meta.xml
<CustomObject>
    <label>Station</label>
    <nameField>
        <label>Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ERDC_Station__c/fields/ERDC_Line__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field indicates the transport line.</description>
    <label>Line</label>
    <referenceTo>ERDC_Line__c</referenceTo>
    <relationshipName>LineStations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERDC_Station__c/fields/ERDC_Parent_Station__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Parent_Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Station</label>
    <referenceTo>ERDC_Station__c</referenceTo>
    <relationshipName>Substations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERDC_Station__c/fields/ERDC_Trip_Count__c.field-meta.xml
<CustomField>
    <fullName>ERDC_Trip_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ERDC_Trip_Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RFID_TicketValidationMachine__e/RFID_TicketValidationMachine__e.object-meta.xml
<CustomObject>
    <description>This platform event takes the input from ticket validation machines.</description>
    <label>Ticket Validation Machine Event</label>
    <pluralLabel>Ticket Validation Machines Events</pluralLabel>
</CustomObject>

force-app/main/default/classes/ERDC_MapController.cls
/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-21
* @description This is a controller class for ERDC_Map Lightning Web Component
********************************************************************************************************/
public without sharing class ERDC_MapController {
/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-25
* @description This method returns a list of all Main Stations
* @param List<RFID_TicketValidationMachine__e>
********************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<ERDC_Station__c> getStationInfo(){
        return [
            SELECT Id,
                Name,
                ERDC_Line__c,
                ERDC_Trip_Count__c,
                ERDC_Location__Latitude__s,
                ERDC_Location__Longitude__s,
                (
                    SELECT Id,
                        Name,
                        Erdc_Trip_Count__c
                    FROM Substations__r
                )
            FROM ERDC_Station__c
            WHERE RecordTypeId = :ERDC_GlobalUtilityConstants.MAIN_STATION_RECORD_TYPE_ID
        ];
    }

/********************************************************************************************************
* @author Andrei Banu
* @date 2021-10-25
* @description This method returns a list of all Lines
* @param List<RFID_TicketValidationMachine__e>
********************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<ERDC_Line__c> getLineInfo(){
        return [
            SELECT Id,
                Name,
                ERDC_Coordinates__c,
                ERDC_Map_Color__c            
            FROM ERDC_Line__c
        ];
    }
}